controller_list:
  - name: fake_scara_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
initial:  # Define initial robot poses per group
  - group: scara
    pose: default_pose